### ISSUE TITLE
504 error

### ISSUE THREAD

**Issue by magicmirror24** [mykle1/MMM-WeatherOrNot#11]
The module has been working perfectly up until today. When MM loads, it says “504 internal server error - nginx.” I restarted MM but I’m still getting the error.  Any idea how to fix?

**Comment by mykle1** [comment]
A 504 error is a server timeout error which could mean the data source was having trouble fulfilling the request for data. It could also mean that your internet was having an issue at the time. I loaded the module and it fired right up so I'm not seeing this behavior, nor has anyone else reported the same. Assuming that you didn't alter any of the module files I would suggest you try again or isolate the module (so that others are disabled) to see if there is a conflict. You could also delete the module folder and re-install to see if that helps. 

If you require more help then please post a topic on the magicMirror forum and I'll be glad to help you there
