### ISSUE TITLE
Little help needed

### ISSUE THREAD

**Issue by Itonkic** [mykle1/MMM-WeatherOrNot#2]
Is there any way to increase font size on?
I tried everything in custom.css in debug it says that size is changed but not visible

**Comment by mykle1** [comment]
Unfortunately, you can't change font size because this is simply a weather widget inside of an iframe. The options given work because the widget supports them. Font size is not supported by the widget. Sorry. Peace!

You could try some of the other fonts. Perhaps you will find one that is better suited for you.
Again, my apologies
